version: '3.8'

services:
    chat-app:
        container_name: chat-app
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3001:3001
        volumes:
            - .:/app

# 1 Run compose file for build :- docker-compose up --build -d
# 2 Stop compose file :- docker-compose down
# 3 Docker logs :- docker logs container-id
# 4 Docker stop :- docker stop
# 5 Docker remove :- docker rm container-id 